Appdomain Disposed
Test Suite Dump
#0: TestProj/Default - 
#1: Default - 
#2: TestProj - 
#3: Calculator - 
#4: Add two numbers - TestAssembly:TestProj/Feature:Calculator/Scenario:Add+two+numbers
End: Test Suite Dump
Scheduler: considering #4 for thread #0
Scheduler: using #4 for thread #0
Test #4 is scheduled for thread #0
Thread #0: creating new test thread executor for TestProj, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (target: Default)
Loading SpecRun type 'TechTalk.SpecRun.Framework.TestAssemblyExecutor' from: C:\Users\mhernandez\AppData\Local\Temp\VisualStudioTestExplorerExtensions\SpecRun.Runner.1.2.0\tools\TechTalk.SpecRun.Framework.Executor.dll
Test #4/0 is started on thread #0
B:Given I have entered 50 into the calculator
T:done: CalculatorSteps.GivenIHaveEnteredIntoTheCalculator(50) (0.0s)
B:And I have also entered 70 into the calculator
T:done: CalculatorSteps.GivenIHaveAlsoEnteredIntoTheCalculator(70) (0.0s)
B:When I press add
T:done: CalculatorSteps.WhenIPressAdd() (0.0s)
B:Then the result should be 120 on the screen
T:error: Assert.Fail failed. These two numbers are not the same: 
Scheduler: dequeuing a rescheduled item: 4
Scheduler: considering #4 for thread #0
Scheduler: using #4 for thread #0
Test #4 is scheduled for thread #0
Test #4 is finished on thread #0 as Failed within 0.1158291 seconds
Test #4/1 is started on thread #0
B:Given I have entered 50 into the calculator
T:done: CalculatorSteps.GivenIHaveEnteredIntoTheCalculator(50) (0.0s)
B:And I have also entered 70 into the calculator
T:done: CalculatorSteps.GivenIHaveAlsoEnteredIntoTheCalculator(70) (0.0s)
B:When I press add
T:done: CalculatorSteps.WhenIPressAdd() (0.0s)
B:Then the result should be 120 on the screen
T:error: Assert.Fail failed. These two numbers are not the same: 
Scheduler: dequeuing a rescheduled item: 4
Scheduler: considering #4 for thread #0
Scheduler: using #4 for thread #0
Test #4 is scheduled for thread #0
Test #4 is finished on thread #0 as Failed within 0 seconds
Test #4/2 is started on thread #0
B:Given I have entered 50 into the calculator
T:done: CalculatorSteps.GivenIHaveEnteredIntoTheCalculator(50) (0.0s)
B:And I have also entered 70 into the calculator
T:done: CalculatorSteps.GivenIHaveAlsoEnteredIntoTheCalculator(70) (0.0s)
B:When I press add
T:done: CalculatorSteps.WhenIPressAdd() (0.0s)
B:Then the result should be 120 on the screen
T:error: Assert.Fail failed. These two numbers are not the same: 
Test #4 is finished on thread #0 as Failed within 0 seconds
Appdomain Disposed
Total: 1 (test executions: 3)
Succeeded: 0
Ignored: 0
Pending: 0
Skipped: 0
Failed: 1
